name: Build Yocto Image for Raspberry Pi 3

on:
  push:
    branches:
      - main  # Change to your branch name if needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget

    - name: Install Required Dependencies
      run: |
        sudo apt-get install -y repo
        sudo apt-get install -y python3 python3-pip

    - name: Clone Yocto Repo and Set Up
      run: |
        git clone https://github.com/agherzan/meta-raspberrypi.git
        cd meta-raspberrypi
        git checkout dunfell  # or another appropriate branch version

    - name: Set up Yocto environment
      run: |
        source ./oe-init-build-env
        echo 'BBLAYERS += "${TOPDIR}/../meta-raspberrypi"' >> conf/bblayers.conf
        echo 'MACHINE = "raspberrypi3"' >> conf/local.conf
        echo 'DISTRO = "poky"' >> conf/local.conf

    - name: Add Python Support to Yocto
      run: |
        echo 'IMAGE_INSTALL_append = " python3 python3-pip"' >> conf/local.conf

    - name: Build Yocto Image
      run: |
        bitbake core-image-minimal  # or your custom image name

    - name: Upload Image Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: yocto-image
        path: build/tmp/deploy/images/raspberrypi3/*.img
