name: Build Yocto Image for Raspberry Pi 3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gawk wget git-core diffstat unzip texinfo \
          build-essential chrpath socat cpio python3 python3-pip python3-pexpect \
          xz-utils debianutils iputils-ping libsdl1.2-dev xterm

    - name: Set up build environment
      run: |
        git clone -b dunfell git://git.yoctoproject.org/poky.git
        cd poky
        git clone -b dunfell git://git.yoctoproject.org/meta-raspberrypi.git
        git clone -b dunfell git://git.openembedded.org/meta-openembedded
        source oe-init-build-env build
        echo 'MACHINE = "raspberrypi3"' >> conf/local.conf
        echo 'DL_DIR ?= "${TOPDIR}/downloads"' >> conf/local.conf
        echo 'SSTATE_DIR ?= "${TOPDIR}/sstate-cache"' >> conf/local.conf
        echo 'BBLAYERS ?= " \
          ${TOPDIR}/../poky/meta \
          ${TOPDIR}/../poky/meta-poky \
          ${TOPDIR}/../meta-raspberrypi \
          ${TOPDIR}/../meta-openembedded/meta-oe \
          ${TOPDIR}/../meta-openembedded/meta-python \
        "' > conf/bblayers.conf

    - name: Build image
      run: |
        source poky/oe-init-build-env build
        bitbake rpi-test-image

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: yocto-image-rpi3
        path: build/tmp/deploy/images/raspberrypi3/*.wic.bz2
