name: Yocto Build (Raspberry Pi 3)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Yocto dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gawk wget git-core diffstat unzip texinfo \
            gcc-multilib build-essential chrpath socat cpio python3 python3-pip \
            python3-pexpect xz-utils debianutils iputils-ping libsdl1.2-dev xterm

      - name: Clone Yocto layers
        run: |
          git clone -b kirkstone git://git.yoctoproject.org/poky
          git clone -b kirkstone https://github.com/openembedded/meta-openembedded.git
          git clone -b kirkstone https://github.com/agherzan/meta-raspberrypi.git

      - name: Initialize build environment
        run: |
          source poky/oe-init-build-env build

      - name: Setup local.conf and bblayers.conf
        run: |
          BUILD_DIR=$(pwd)/build

          # Create local.conf
          cat <<EOF > $BUILD_DIR/conf/local.conf
MACHINE = "raspberrypi3"
DISTRO_FEATURES:append = " wifi systemd"
EXTRA_IMAGE_FEATURES:append = " debug-tweaks ssh-server-openssh package-management"

IMAGE_INSTALL:append = " \\
  python3 \\
  python3-pip \\
  python3-setuptools \\
  python3-wheel \\
  python3-distutils \\
  nano \\
  opkg \\
  wpa-supplicant \\
  wireless-tools \\
  dhcpcd \\
  dhcp-client \\
"

ENABLE_UART = "1"
SERIAL_CONSOLE = "115200 ttyAMA0"

ROOTFS_POSTPROCESS_COMMAND += "install_python_packages;"

install_python_packages() {
  echo "Installing Python packages via pip..."
  export PIP_ROOT_USER_ACTION=ignore
  pip3 install pyserial==3.5 requests==2.32.3 supabase==2.13.0
}
EOF

          # Create bblayers.conf
          cat <<EOF > $BUILD_DIR/conf/bblayers.conf
BBLAYERS ?= " \\
  $(pwd)/poky/meta \\
  $(pwd)/poky/meta-poky \\
  $(pwd)/poky/meta-yocto-bsp \\
  $(pwd)/meta-openembedded/meta-oe \\
  $(pwd)/meta-openembedded/meta-networking \\
  $(pwd)/meta-openembedded/meta-python \\
  $(pwd)/meta-raspberrypi \\
"
EOF

      - name: Build the image
        run: |
          source poky/oe-init-build-env build
          bitbake rpi-test-image

      - name: Upload built image
        uses: actions/upload-artifact@v3
        with:
          name: yocto-rpi3-image
          path: build/tmp/deploy/images/
