name: Build Yocto Image for Raspberry Pi 4

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gawk wget git-core diffstat unzip texinfo gcc \
          build-essential chrpath socat cpio python3 python3-pip \
          python3-pexpect xz-utils debianutils iputils-ping \
          libsdl1.2-dev xterm

    - name: Clone Yocto Layers
      run: |
        git clone -b kirkstone git://git.yoctoproject.org/poky poky
        git clone -b kirkstone git://git.yoctoproject.org/meta-raspberrypi
        git clone -b kirkstone https://github.com/openembedded/meta-openembedded.git
        git clone -b kirkstone https://git.yoctoproject.org/git/meta-virtualization

    - name: Prepare Config
      run: |
        ls -l conf/
        mkdir -p build/conf
        cp conf/local.conf build/conf/local.conf
        cp conf/bblayers.conf build/conf/bblayers.conf

    - name: Build Image
      run: |
        source poky/oe-init-build-env build
        bitbake rpi-test-image

    - name: Upload Output Image
      uses: actions/upload-artifact@v4
      with:
        name: rpi4-image
        path: build/tmp/deploy/images/raspberrypi4/
