
0s
Current runner version: '2.323.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download immutable action package 'actions/checkout@v4'
  Version: 4.2.2
  Digest: sha256:ccb2698953eaebd21c7bf6268a94f9c26518a7e38e27e0b83c1fe1ad049819b1
  Source commit SHA: 11bd71901bbe5b1630ceea73d27597364c9af683
Error: Missing download info for actions/upload-artifact@v3
